format_version: 3
common:
  symlink-toolchain: &symlink-toolchain
    exec:
      command: /bin/bash
      arguments:
        - -c
        - |
          rm -rf /opt/*
          echo "GO REVISION is: $GO_REVISION"
          echo 'SHORT_SHA1=$(echo "$GO_REVISION" | cut -c 1-10)
          [[ -v GO_REVISION ]]; echo $?
          export TOOLCHAIN_BASE_PATH="/opt/grisp/grisp-software/grisp-base"
          export TOOLCHAIN_PATH="$TOOLCHAIN_BASE_PATH/$SHORT_SHA1"
          export GO_PWD=$PWD
          mkdir -p $TOOLCHAIN_BASE_PATH
          ln -s $GO_PWD $TOOLCHAIN_PATH' > grisp.rc
  cleanup-toolchain-build-dir: &cleanup-toolchain-build-dir
    exec:
      command: rm
      arguments:
        - -rf
        - /opt/grisp
pipelines:
  grisp-software:
    group: grisp
    materials:
      github:
        git: https://github.com/grisp/grisp-software.git
    stages:
      - build:
          clean_workspace: true
          jobs:
            build.sh:
              artifacts:
                - build:
                    source: rtems-source-builder/rtems/rsb-report*
                    destination: rsb-reports
                - build:
                    source: rtems-install
                    destination: rtems-install
              tasks:
                - *symlink-toolchain
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        source grisp.rc
                        echo $TOOLCHAIN_PATH
                        pwd
                        ls -al
                        echo "GO REV GH: $GO_REVISION_GITHUB"
                        cd $TOOLCHAIN_PATH
                        ls -al
                        ./build/build.sh
                - *cleanup-toolchain-build-dir
      - deploy-to-aws:
          clean_workspace: true
          jobs:
            deploy:
              tasks:
                - fetch:
                    artifact-origin: gocd
                    pipeline: grisp-software
                    stage: build
                    job: build.sh
                    source: rtems-install
                    destination: rtems-install                                            
                - *symlink-toolchain
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        source grisp.rc
                        cd /opt
                        tar -czf /tmp/grisp_toolchain_arm-rtems5_Linux_$GO_REVISION.tar.gz

