pipelines:
  grisp-software:
    materials:
      github:
        git: https://github.com/grisp/grisp-software.git
    stages:
      - build:
          clean_workspace: true
          jobs:
            build.sh:
              artifacts:
                - rsb-reports:
                    source: rtems-source-builder/rtems/rsb-report*
                    destination: rsb-reports
                - rtems-install:
                    source: rtems-install
                    destination: rtems-install
              tasks:
                exec:
                  command: |
                    /bin/bash -c '
                    GO_PWD=$PWD
                    SHORT_SHA1=$(echo "${GO_REVISION}" | cut -c 1-10)
                    TOOLCHAIN_BASE_PATH="/opt/grisp/grisp-software/grisp-base"
                    TOOLCHAIN_PATH="$TOOLCHAIN_BASE_PATH/$SHORT_SHA1"
                    rm -rf /opt/grisp
                    mkdir -p ${TOOLCHAIN_BASE_PATH}
                    ln -s $GO_PWD $TOOLCHAIN_PATH
                    cd $TOOLCHAIN_PATH; ./build/build.sh
                    unlink $TOOLCHAIN_PATH
                    rm -rf /opt/grisp'



