pipelines:
  grisp-software:
    materials:
      github:
        git: https://github.com/grisp/grisp-software.git
    stages:
      - build:
          clean_workspace: true
          jobs:
            build.sh:
              artifacts:
                - rsb-reports:
                    source: artifacts/rsb-reports
                    destination: rsb-reports
                - rtems-install:
                    source: artifacts/rtems-install
                    destination: rtems-install
              tasks:
                exec:
                  command: |
                    /bin/bash -c '
                    GO_PWD=$PWD
                    SHORT_SHA1=$(echo "${GO_REVISION}" | cut -c 1-10)
                    TOOLCHAIN_PATH="/opt/grisp/grisp-software/grisp-base/$SHORT_SHA1"
                    rm -rf /opt/grisp
                    mkdir -p ${TOOLCHAIN_PATH}
                    shopt -s dotglob && cp ./* "${TOOLCHAIN_PATH}"
                    cd $TOOLCHAIN_PATH; ./build/build.sh
                    mkdir -p $GO_PWD/artifacts/rsb-reports
                    mkdir -p $GO_PWD/artifacts/rtems-install
                    cp $TOOLCHAIN_PATH/rtems-source-builder/rtems/rsb-report* $GO_PWD/artifacts/rsb-reports
                    mv /opt/grisp/*/*/*/rtems-install $GO_PWD/artifacts/rtems-install
                    rm -rf /opt/grisp'



